version: "3.3"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    #image: openlmis/nginx:${OL_NGINX_VERSION}
    image: elmislesotho/nginx:${OL_NGINX_VERSION}
    ports:
      - "${OL_HTTP_PORT:-80}:80"
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
      NGINX_TIMEOUT: '300s'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]

  reference-ui:
    image: elmislesotho/reference-ui:${OL_REFERENCE_UI_VERSION}
    env_file: settings.env
    depends_on: [consul]

  requisition:
    image: elmislesotho/requisition:${OL_REQUISITION_VERSION}
    env_file: settings.env
    environment:
      #JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
      JAVA_OPTS: >
        -server
        -Xms1024m
        -Xmx3072m
        -XX:+UseG1GC
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -Xss512k
        -XX:+PrintGCDetails
        -XX:+PrintGCDateStamps
        -Xloggc:/var/log/requisition/gc.log
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  referencedata:
    image: elmislesotho/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: settings.env
    environment:
      #JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
      JAVA_OPTS: >
        -server
        -Xms1024m
        -Xmx3072m
        -XX:+UseG1GC
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -Xss512k
        -XX:+PrintGCDetails
        -XX:+PrintGCDateStamps
        -Xloggc:/var/log/referencedata/gc.log
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  auth:
    image: elmislesotho/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  notification:
    image: elmislesotho/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  fulfillment:
    image: elmislesotho/fulfillment:${OL_FULFILLMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  cce:
    image: openlmis/cce:${OL_CCE_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  stockmanagement:
    image: elmislesotho/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      #JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      JAVA_OPTS: >
        -server
        -Xms1024m
        -Xmx3072m
        -XX:+UseG1GC
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -Xss512k
        -XX:+PrintGCDetails
        -XX:+PrintGCDateStamps
        -Xloggc:/var/log/stockmanagement/gc.log
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  # prepacking:
  #   image: elmislesotho/prepacking:${OL_PREPACKING_VERSION}
  #   env_file: settings.env
  #   environment:
  #     JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
  #   volumes:
  #     - 'service-config:/config'
  #   depends_on: [log, db]
  #   command: ["/wait-for-postgres.sh", "/run.sh"]

  # dispensing:
  #   image: elmislesotho/dispensing:${OL_DISPENSING_VERSION}
  #   env_file: settings.env
  #   environment:
  #     JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
  #   volumes:
  #     - 'service-config:/config'
  #   depends_on: [log, db]
  #   command: ["/wait-for-postgres.sh", "/run.sh"]

  report:
    image: openlmis/report:${OL_REPORT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  buq:
    image: openlmis/buq:${OL_BUQ_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [ log, db ]
    command: [ "/wait-for-postgres.sh", "/run.sh" ]

  hapifhir:
    restart: always
    image: openlmis/hapifhir:${OL_HAPIFHIR_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    
  diagnostics:
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    env_file: settings.env
    networks:
      default:
        aliases:
          - olmis-db
    depends_on: [consul]

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config

  ftp:
    image: driesva/proftpd:latest
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on: [consul]

  redis:
    image: redis:3.2.12
    depends_on: [consul]

  pointofdelivery:
    image: elmislesotho/pointofdelivery:${OL_POINTOFDELIVERY_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'pointofdelivery-extensions:/extensions'
      - 'service-config:/config'
    depends_on: [log, db]

  # example-extensions:
  #   image: openlmis/openlmis-example-extensions:latest
  #   volumes:
  #     - 'example-extensions:/extensions'

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
  pointofdelivery-extensions:
    external: false
